name: Cache Prime Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        id: cache-python-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-53a55a9

      - name: prime-cache-53a55a9
        run: echo "Cache status: ${{ steps.cache-python-deps.outputs.cache-hit }}"
